

analyzers:
  HardwareInterfaces:
    type: diagnostic_aggregator/AnalyzerGroup
    path: HardwareInterfaces
    analyzers:
      Sarkofag:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sarkofag
        startswith: 'Sarkofag'

     

